plugins {
    id 'java'
}

group = 'com.db'
version = '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()

    // Paper API
    maven {
        url = "https://repo.papermc.io/repository/maven-public/"
    }

    // XSeries (IMPORTANT)
    maven {
        url = "https://jitpack.io"
    }
}

dependencies {
    // Paper API
    compileOnly "io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT"

    // XSeries (FIXES YOUR ERROR)
    compileOnly "com.github.cryptomorin:XSeries:9.6.1"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}